name: Auto Zip Meeting Folders

on:
  push:
    paths:
      - 'acm/**'
      - 'fbos/**'
      - 'rac/**'
      - 'frc/**'
      - 'herc/**'

jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Zip folders
        run: |
          for dir in acm fbos rac frc herc; do
            if [ -d "$dir" ]; then
              zip -r "${dir}/${dir}.zip" "$dir" -x "*.zip"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add */**/*.zip
          git diff --cached --quiet || git commit -m "Auto-zipped meeting folders on push"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/bufoes/bufoes.github.io.git
          git push origin main
