name: Auto Zip Meeting Folders

on:
  push:
    paths:
      - 'acm/**'
      - 'fbos/**'
      - 'rac/**'
      - 'frc/**'
      - 'herc/**'

jobs:
  zip:
    runs-on: ubuntu-latest
    
    # Explicit permissions declaration
    permissions:
      contents: write
      pull-requests: write
      actions: read
      checks: write
      statuses: write
      deployments: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use the default GITHUB_TOKEN with write permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip folders
        run: |
          for dir in acm fbos rac frc herc; do
            if [ -d "$dir" ]; then
              zip -r "${dir}/${dir}.zip" "$dir" -x "*.zip"
            fi
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-zipped meeting folders on push"
          branch: main
          file_pattern: '*/**/*.zip'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
