name: Create and Deploy ZIPs with Jekyll

on:
  workflow_dispatch:
  push:
    paths:
      - 'acm/**'
      - 'fbos/**'
      - 'rac/**'
      - 'frc/**'
      - 'herc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-zips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install zip tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip p7zip-full

      - name: Create validated ZIPs
        run: |
          set -euo pipefail
          mkdir -p zips

          # Create ZIPs in a way that survives Jekyll processing
          for dir in acm fbos rac frc herc; do
            if [ -d "$dir" ]; then
              echo "Creating ZIP for $dir"
              # Use 7zip for more reliable binary preservation
              7z a -tzip -mx=9 "zips/$dir.7z" "$dir/*.pdf"
              # Rename to .zip after creation
              mv "zips/$dir.7z" "zips/$dir.zip"
              
              # Verify ZIP integrity
              if ! unzip -tq "zips/$dir.zip"; then
                echo "ERROR: Failed to create valid ZIP"
                exit 1
              fi
              ls -lh "zips/$dir.zip"
            else
              echo "Directory $dir not found"
            fi
          done

      - name: Add ZIP mime type configuration
        run: |
          echo '{
            "version": 1,
            "mimeTypes": {
              ".zip": "application/zip"
            }
          }' > _headers
          echo '*.zip binary' > .gitattributes

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config core.autocrlf false
          
          git add zips/ _headers .gitattributes
          if ! git diff --cached --quiet; then
            git commit -m "Update ZIP archives [skip ci]"
            git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
            git push
          else
            echo "No changes to commit"
          fi