name: Auto Zip Meeting Folders

on:
  push:
    paths:
      - 'acm/**'
      - 'fbos/**'
      - 'rac/**'
      - 'frc/**'
      - 'herc/**'

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Zip folders
        run: |
          for dir in acm fbos rac frc herc; do
            if [ -d "$dir" ]; then
              zip -r "${dir}/${dir}.zip" "$dir" -x "*.zip"
            fi
          done

      - name: Commit and push ZIP files
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git add acm/acm.zip fbos/fbos.zip rac/rac.zip frc/frc.zip herc/herc.zip
          git diff --cached --quiet || git commit -m "Auto-zipped meeting folders"
          git push
