name: Auto Zip Meeting Folders

on:
  push:
    paths:
      - 'acm/**'
      - 'fbos/**'
      - 'rac/**'
      - 'frc/**'
      - 'herc/**'

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip folders
        run: |
          for dir in acm fbos rac frc herc; do
            if [ -d "$dir" ]; then
              zip -r "${dir}/${dir}.zip" "$dir" -x "*.zip"
            fi
          done

      - name: Commit and push ZIPs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add */*.zip
          git commit -m "Auto-zipped folders on push"
          git push
