name: Auto Zip PDFs from Meeting Folders

on:
  push:
    paths:
      - 'acm/**/*.pdf'
      - 'fbos/**/*.pdf'
      - 'rac/**/*.pdf'
      - 'frc/**/*.pdf'
      - 'herc/**/*.pdf'

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Create zips only if PDFs changed
        run: |
          mkdir -p zips .checksums
          changed=false

          for dir in acm fbos rac frc herc; do
            if [ ! -d "$dir" ]; then
              echo "Skipping $dir: directory does not exist"
              continue
            fi

            hash_file=".checksums/$dir.sha"

            # Compute hash of all PDFs in folder (names + sizes)
            current_hash=$(find "$dir" -type f -name "*.pdf" -print0 | \
              xargs -0 stat --format '%n %s' | sha256sum | cut -d' ' -f1)

            previous_hash=""
            if [ -f "$hash_file" ]; then
              previous_hash=$(cat "$hash_file")
            fi

            if [ "$current_hash" != "$previous_hash" ]; then
              echo "Zipping $dir: changes detected"

              # Only zip if PDFs exist
              pdf_count=$(find "$dir" -type f -name "*.pdf" | wc -l)
              if [ "$pdf_count" -gt 0 ]; then
                # Zip PDFs inside the directory, store zip in ../zips folder, exclude any .zip files
                (cd "$dir" && zip -r "../zips/$dir.zip" . -i '*.pdf' -x '*.zip')
                ls -lh "../zips/$dir.zip"
              else
                echo "No PDFs found in $dir, skipping zip."
                rm -f "zips/$dir.zip"
              fi

              echo "$current_hash" > "$hash_file"
              changed=true
            else
              echo "No change in $dir"
            fi
          done

          if [ "$changed" = true ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .checksums zips
            if ! git diff --cached --quiet; then
              git commit -m "Selective ZIP update based on PDF changes"
              git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
              git push
            else
              echo "No changes to commit."
            fi
          else
            echo "No ZIP updates needed."
          fi
