name: Auto Zip PDFs from Meeting Folders

on:
  push:
    paths:
      - 'acm/**'
      - 'fbos/**'
      - 'rac/**'
      - 'frc/**'
      - 'herc/**'
      - '!zips/**'  # Exclude zip directory
      - '!.checksums/**'  # Exclude checksums directory

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip p7zip-full

      - name: Create validated zips
        run: |
          set -euo pipefail
          mkdir -p zips .checksums
          changed=false

          expected_dirs=("acm" "fbos" "rac" "frc" "herc")

          create_valid_zip() {
            local src_dir=$1
            local zip_file=$2
            
            temp_dir=$(mktemp -d)
            trap 'rm -rf "$temp_dir"' EXIT
            
            find "$src_dir" -name '*.pdf' -exec cp {} "$temp_dir" \;
            
            (cd "$temp_dir" && zip -9 -r "$OLDPWD/$zip_file" .)
            
            if ! unzip -tq "$zip_file"; then
              echo "ERROR: Created invalid ZIP file, trying 7zip..."
              7z a -tzip "$zip_file" "$temp_dir/*"
              if ! unzip -tq "$zip_file"; then
                echo "ERROR: Failed to create valid ZIP file"
                exit 1
              fi
            fi
          }

          for dir in "${expected_dirs[@]}"; do
            echo "Processing $dir..."
            hash_file=".checksums/$dir.sha"
            zip_file="zips/$dir.zip"

            if [ ! -d "$dir" ]; then
              echo "Directory $dir does not exist"
              [ -f "$zip_file" ] && rm -f "$zip_file" && changed=true
              [ -f "$hash_file" ] && rm -f "$hash_file" && changed=true
              continue
            fi

            current_hash=$(find "$dir" -type f -name "*.pdf" -print0 2>/dev/null | \
              xargs -0 stat --format '%n %s' 2>/dev/null | sha256sum | cut -d' ' -f1 || true)

            previous_hash=""
            [ -f "$hash_file" ] && previous_hash=$(cat "$hash_file")

            if [ ! -f "$zip_file" ] || [ "$current_hash" != "$previous_hash" ] || \
               { [ -f "$zip_file" ] && ! unzip -tq "$zip_file"; }; then
              echo "Update needed for $dir"
              pdf_count=$(find "$dir" -name '*.pdf' | wc -l)
              
              if [ "$pdf_count" -gt 0 ]; then
                echo "Zipping $pdf_count PDF(s) from $dir"
                create_valid_zip "$dir" "$zip_file"
                ls -lh "$zip_file"
                echo "$current_hash" > "$hash_file"
                changed=true
              else
                echo "No PDFs found, removing zip if exists"
                rm -f "$zip_file"
                changed=true
              fi
            else
              echo "No changes needed for $dir"
            fi
          done

          if [ "$changed" = true ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config core.autocrlf false

            git add .checksums zip
            git commit -m "Auto-update: Regenerated ZIP files [skip ci]" || exit 0
            
            git remote set-url origin "https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi